version: "3"

#se inician los servicos 
services:
#Se inicia el servicio de grafana 
  grafana:
  #Se coloca la direccion de la imagen
    image: grafana/grafana
    #Se asigna un nombre para el servicio servicio
    container_name: grafana
    #Indicamos que siempre se inicie
    restart: always
    #Se selecciona el el puerto
    ports:
      - 3000:3000
      #Se selecciona el nombre del networks
    networks:
      - grafana_network
      #Se agrega la direccion 
    volumes:
      - grafana_data:/var/lib/grafana
      #Se agrega la dependencia
    depends_on:
      - influxdb
  #Se inicia el servicio Influxdb
  influxdb:
    #Se ingresa la direccion de la imagen
    image: influxdb:latest
    #Se le asigna un nombre para el servicio
    container_name: influxdb
    #Indicamos que siempre se inicie
    restart: always
     #Seleccionamos el puerto
    ports:
      - 8086:8086
      #Se selecciona el nombre del networks
    networks:
      - grafana_network
      #ingresamos la direccion 
    volumes:
      - influxdb_data:/var/lib/influxdb
      #Se ingresa la cofiguracion de la base de datos 
    environment:
      - INFLUXDB_DB=grafana               #Agregamos nombre de la base de datos 
      - INFLUXDB_USER=grafana             #Agregamos el usuario de la base de datos
      - INFLUXDB_USER_PASSWORD=password   #Agregamos el password para el usuario
      - INFLUXDB_ADMIN_ENABLED=true       
      - INFLUXDB_ADMIN_USER=admin         #Agregamos el nombre para el admin
      - INFLUXDB_ADMIN_PASSWORD=password  #Agregamos la contraseña para el administrador
  #Se inician los servicios 
  nodered:
  #Se ingrsa el nombre del servicio
    container_name: Node-red
    #Se agrega la direccion de la imagen de node-red
    image: nodered/node-red:latest
    #Indicamos que siempre se inicie
    restart: always
    #Se le asgina un puerto
    ports:
      - 1880:1880
    #Se configuran los networds
    networks:
      - grafana_network
      #Se agrega el volumen
    volumes:
      - nodered_data:/var/lib/nodered
networks:
  grafana_network:
  #Se agregan los volumenes de grafana, influxdb y node-red
volumes:
  grafana_data:
  influxdb_data:
  nodered_data:
